### ISSUE TITLE
HMS Keys

### ISSUE THREAD

**Issue by tfluehmann** [terraform-google-modules/terraform-google-kms#24]
Dear all

I try to create a keyring with keys which are stored in an HMS instead of software protection.
I haven't seen any option how to specify where the key is stored.
Is this use case supported already?

Thanks in advance

**Comment by morgante** [comment]
It looks like this isn't supported yet, we'd need to add a variable exposing the [protection level](https://www.terraform.io/docs/providers/google/r/kms_crypto_key.html#protection_level). Happy to accept a PR.

**Comment by thiagonache** [comment]
I'll see if I can take this one on next weekend.

**Comment by thiagonache** [comment]
@morgante Please, take a look in the PR #27 once you get a chance. I used a simple approach.

**Comment by thiagonache** [comment]
@morgante can we close this?
