### ISSUE TITLE
Add support for Terraform 0.12

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-kms#3]

**Comment by bohdanyurov-gl** [comment]
- Migrate to the new syntax
- Make sure that type for variables is defined
- Remove instances of unnecessary string interpolation from the code base
- Remove unnecessary "element" calls
- Make sure integration tests pass locally
- Switch to docker image for terraform 0.12 (version 2.0.0)
- Update CHANGELOG.md
- Update READMEmd, make sure latest 0.11 release is specified
