### ISSUE TITLE
Outputs should depend on role bindings

### ISSUE THREAD

**Issue by jaketf** [terraform-google-modules/terraform-google-kms#30]
I've run into an issue where I add the `module.kms.keyring_resource` to a `depends_on` block of a null resource which uses a gcloud local-exec to use this key to encrypt something and upload to GCS. (For context's sake this is to provision random kerberos secrets for dataproc cluster to GCS for an example data lake).

Behavior of my module becomes non-deterministic because there is a corner case where the null resource tries to use the keyring before the appropriate iam permission has been set because there is no dependency on the iam binding.

This will resolve itself after a few applies because eventually the iam binding will have been deployed before the local-exec is attempted.
However, it would be cleaner if I could depend on the iam bindings created by this module.

If there is a better way to do this please let me know and I will close this issue.

**Comment by bharathkkb** [comment]
Hi @jaketf 
Would it make more sense for  `keyring_resource` output within this module to depend_on the varios `google_kms_crypto_key_iam_binding`s before it resolves? I am thinking similar to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/19a9e9c57b94d1332867a6c29b052e99785e2820/outputs.tf#L48

**Comment by jaketf** [comment]
Yes, that would certainly work for me!
