### ISSUE TITLE
Does not play nicely with terraform destroy when only single key

### ISSUE THREAD

**Issue by jaketf** [terraform-google-modules/terraform-google-kms#32]
When running `terraform destroy` on a workspace that uses this module to provision a single key, I get the following error which seems internal to this module despite using `prevent_destroy=false`.

```
Error: Invalid function argument
  on .terraform/modules/test_data_lake.kms/terraform-google-kms-1.2.0/main.tf line 18, in locals:
  18:   keys_by_name = zipmap(var.keys, var.prevent_destroy ? slice(google_kms_crypto_key.key[*].self_link, 0, length(var.keys)) : slice(google_kms_crypto_key.key_ephemeral[*].self_link, 0, length(var.keys)))
    |----------------
    | var.keys is list of string with 1 element
Invalid value for "end_index" parameter: end index must not be greater than
the length of the list.
```

Do the integration tests check behavior on destroy? It seems this module's integration test has two keys perhaps this behavior is unique to when this module is used to provision only a single key.

config that produced this issue:
```hcl
module "kms" {
  source  = "terraform-google-modules/kms/google"
  version = "~> 1.2"

  project_id = var.project
  location   = split("-", var.region)[0]
  keyring    = var.kms_key_ring
  keys               = [var.dataproc_kms_key]
  set_owners_for     = [var.dataproc_kms_key]
  set_encrypters_for = [var.dataproc_kms_key]
  set_decrypters_for = [var.dataproc_kms_key]
  owners             = ["user:${var.data_lake_super_admin}"]
  encrypters = [
    module.service_accounts.iam_emails["${var.kdc_cluster}-sa"]
  ]
  decrypters = [
    join(",", [
      module.service_accounts.iam_emails["${var.kdc_cluster}-sa"],
      module.service_accounts.iam_emails["${var.metastore_cluster}-sa"],
      module.service_accounts.iam_emails["${var.analytics_cluster}-sa"],
    ])
  ]
  prevent_destroy = "false"
}
```

**Comment by bharathkkb** [comment]
Hi @jaketf 
Did any out of band changes happen to the keys? 

Integration tests do check destroy behavior and I also tried to repro using the test example and a single key and that destroyed fine too. The error seems to originating from the `slice` func. What provider/TF version are you using?

**Comment by jaketf** [comment]
Hmm I wonder if my state has been corrupted. 
It seems somehow the `var.keys` contains a single element but `google_kms_crypto_key.key[*]` is empty.
I'm seeing very similar issue w/ `slice` complaining about `end_index` > list length in the google storage buckets module.
closing this issue as the observed behavior is not unique to this module and likely a bad state file or something.
```
terraform -version
Terraform v0.12.28
+ provider.google v3.32.0
+ provider.google-beta v3.32.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

**Comment by jaketf** [comment]
I've confirmed with `terraform state list module.kms` that the state file is unaware of any resources associated with this module.
I'll have to dig in with customer to if there is an issue with the state file.
