### ISSUE TITLE
Thoughts on refactoring the module to use an authoritative policy?

### ISSUE THREAD

**Issue by soggycactus** [terraform-google-modules/terraform-google-kms#36]
What are your thoughts on refactoring this module to receive a more detailed `keys` variable with all of its metadata, and managing the IAM for each key using an authoritative policy?

For reference, I created a module at a previous job that did this pretty well: https://github.com/soggycactus/terraform-google-kms-keyring

We looked at using this module, as we prefer not to write our own Terraform if there's an officially support module for it. But we felt it was best to manage our KMS keys using an authoritative policy.

**Comment by morgante** [comment]
I'm not quite sure I follow the ask here.

If you want to set the key IAM authoritatively you could use `mode = "authoritative"` - does that work for your use case?

**Comment by morgante** [comment]
I'm not sure we want to preclude setting any IAM outside the module, but we could probably add support for additional roles.

**Comment by soggycactus** [comment]
> I'm not sure we want to preclude setting any IAM outside the module, but we could probably add support for additional roles.

Fair enough, I'll close this out
